name: Deploy Dashboard

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Homer
        uses: actions/checkout@v3
        with:
          repository: "bastienwirtz/homer"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: dash

      - name: Build and Copy Config
        run: yarn install && yarn build && cp dash/config.yml dist/assets/ && cp dash/CNAME dist/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
